export const regularIcons = [
    "fa-regular fa-address-book",
    "fa-regular fa-address-card",
    "fa-regular fa-bell",
    "fa-regular fa-calendar",
    "fa-regular fa-chart-bar",
    "fa-regular fa-check-circle",
    "fa-regular fa-circle",
    "fa-regular fa-clipboard",
    "fa-regular fa-clock",
    "fa-regular fa-clone",
    "fa-regular fa-comment",
    "fa-regular fa-compass",
    "fa-regular fa-copy",
    "fa-regular fa-credit-card",
    "fa-regular fa-envelope",
    "fa-regular fa-file",
    "fa-regular fa-folder",
    "fa-regular fa-heart",
    "fa-regular fa-star",
    "fa-regular fa-thumbs-up",
    "fa-regular fa-trash-alt",
    "fa-regular fa-user",
  ];
  